export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
//cat users DB
export const REQUEST_ROBOTS_PENDING =  'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESSS =  'REQUST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED =  'REQUEST_ROBOTS_FAILED';
//Next page
export const REQUEST_ROBOTS_NEXTPAGE =  'REQUEST_ROBOTS_NEXTPAGE';
export const CHECK_ROBOTS_LASTPAGE =  'CHECK_ROBOTS_LASTPAGE'